id: 3generate_app_credentials
learningObjectives:
  - Generate app credentials.
hints:
  - Store your credentials securely to prevent unauthorized access.
  - Review the [apps credentials
    guide](https://aps.autodesk.com/en/docs/apps-credentials-guide).
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's create your first app by going to your Autodesk dashboard and :instruction[Clicking on Create Application].
          - text: Choose 'Traditional Web App' and name your application.
          - text: After clicking create application you will see your application credentials.
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now let's ensure that there is a secure communication between your app and Autodesk services.
          - text: ":instruction[Copy your Client ID and Secret], protect them well! These credentials are essential for API access and should be stored securely."
          - text: You're now ready for your app integration. Use these credentials to authenticate API requests and start building your integration.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
