id: create_aps_account
learningObjectives:
  - Create an Autodesk Platform Services account.
hints:
  - Make sure to use a reliable email address.
  - Keep track of your Autodesk credentials.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's set up your Autodesk account. This account will give you access to Autodesk Platform Services.
          - text: Visit [Autodesk Platform Services](https://aps.autodesk.com). This is the official site where you can manage your Autodesk services.
          - text: Click 'Sign Up'—quick and easy. Fill in the required information such as your name, email, and password.
          - text: Ensure email confirmation to activate your account. Check your email for a confirmation link and click it to activate your account.
          - text: Once ready, we move to your next adventure. With your account set up, you can now explore and integrate Autodesk services.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
