id: execute_validate_bim360
learningObjectives:
  - Execute and validate BIM 360 workflows.
hints:
  - Check for proper RVT file format.
  - Ensure the BIM 360 folder is correctly configured for monitoring.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Time to make magic happen. We will now execute and validate BIM 360 workflows.
          - text: Log into your Autodesk application. Ensure you have the necessary permissions to access BIM 360.
          - text: Upload an RVT file into a monitored BIM 360 folder. This will trigger the automated workflows configured for the folder.
          - text: System will detect the upload and trigger workflows. These workflows may include file validation, issue detection, and more.
          - text: Verify issues in BIM 360 UI. Check the BIM 360 interface for any issues or notifications related to the uploaded file.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
