id: generate_app_credentials
learningObjectives:
  - Generate app credentials.
hints:
  - Store your credentials securely to prevent unauthorized access.
  - Review the [apps credentials
    guide](https://aps.autodesk.com/en/docs/apps-credentials-guide).
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Time to authenticate your app.
          - text: Log into Autodesk and navigate to 'Apps & Keys'.
          - text: "Here lies digital magic: create your app."
          - text: Receive your Client ID and Secret—protect them well!
          - text: You're now ready for your app integration.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
