id: generate_app_credentials
learningObjectives:
  - Generate app credentials.
hints:
  - Store your credentials securely to prevent unauthorized access.
  - Review the [apps credentials
    guide](https://aps.autodesk.com/en/docs/apps-credentials-guide).
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Time to authenticate your app. This is a crucial step to ensure secure communication between your app and Autodesk services.
          - text: Log into Autodesk and navigate to 'Apps & Keys'. This section allows you to manage your app credentials.
          - text: "Here lies digital magic: create your app. Fill in the required details such as app name, description, and platform."
          - text: Receive your Client ID and Secret—protect them well! These credentials are essential for API access and should be stored securely.
          - text: You're now ready for your app integration. Use these credentials to authenticate API requests and start building your integration.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
