id: run_configure_codespace
learningObjectives:
  - Configure your app.
hints:
  - Use a text editor that highlights yaml syntax to avoid formatting errors.
  - Check for typos in the variable names or paths.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Bring your creation to life in Codespace! This is where your project starts to take shape.
          - text: Navigate to the root directory of your project where all the main files are located.
          - text: Open the `docker-compose.yml` file in your project. This file contains the configuration for your Docker containers.
          - text: "Edit the environmental variables: CLIENT_ID and CLIENT_SECRET. These variables are crucial for the authentication and authorization of your app."
          - text: Save the changes you made to the `docker-compose.yml` file to ensure the new configurations are applied.
          - text: Launch your app using the appropriate command, such as `docker-compose up`, and witness its wonders! Your app should now be running with the updated configurations.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
